AWSTemplateFormatVersion: '2010-09-09'
Description: Creation of an EC2 instance
Parameters:
  AMI:
    Description: AMI to start Ec2 instance from
    Type: String
    Default: ami-0fa49cc9dc8d62c84
  
  AZ:
    Type: AWS::EC2::AvailabilityZone::Name

  USER:
    Description: USER launching the stack
    Type: String
    Default: clarkem8
    
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName

  InstanceType:
    Type: String
    Default: t2.micro
    AllowedValues: 
      - t2.micro
      - t2.small
    Description: Ec2 instance to be launched

Mappings:
  RegionMap:
    us-east-2:
      VPV: vpc-0ec22768d1195d469
      SG: sg-0879ae26098371b0d
      IAM: arn:aws:iam::777448057161:instance-profile/MC-IAM-May-15-v1-RootInstanceProfile-1IKF6FR5H4TTP

  AZMap:
    us-east-2a:
      Subnet: subnet-043e42106c4777d0c
    us-east-2b:
      Subnet: subnet-0d70d602a3ce5d85c


Resources:
  EC2LaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateName:
        Fn::Join:
          - .
          - - Ref: AWS::StackName
            - 'ec2-launch-template'
      LaunchTemplateData:
        ImageId: 
          Ref: AMI
        IamInstanceProfile:
          Arn:
            Fn::FindInMap: [RegionMap, Ref: "AWS::Region", IAM]
        InstanceType:
          Ref: InstanceType
        KeyName: 
          Ref: KeyName
        NetworkInterfaces:
          - SubnetId:
              Fn::FindInMap: [AZMap, Ref: AZ, Subnet]
            DeviceIndex: 0
            Groups:
              - Fn::FindInMap: [RegionMap, Ref: "AWS::Region", SG]
        UserData:
          Fn::Base64: !Sub |
            #!/bin/bash -x
            echo "Running userdata"
            
            export USER="${USER}"
            
            useradd $USER
            yum install git -y
            GIT_REPO=environment
            export GIT_PATH=/home/$USER/github
            echo "Git path is - $GIT_PATH"
            sudo -i -u $USER git clone "https://github.com/clarkem8/$GIT_REPO.git" $GIT_PATH/$GIT_REPO
            
            $GIT_PATH/$GIT_REPO/setup/install_packages.sh
            sudo -i -u $USER $GIT_PATH/$GIT_REPO/setup/user_setup.sh
            
        TagSpecifications:
          - ResourceType: instance
            Tags:
              - Key: Name
                Value:
                  !Join
                    - '-'
                    - - Ref: AWS::StackName
                      - 'EC2-Instance'
              - Key: User
                Value: 
                  Ref: USER
               
  Ec2Instance: 
    Type: AWS::EC2::Instance
    Properties:
      LaunchTemplate:
        LaunchTemplateId:
          Ref: EC2LaunchTemplate
        Version: "1"
